nginx:
    build: ./nginx
    links:
        - node:node
    ports:
        - "80:80"
node:
    build: ./node
    links:
        - mongodb
    ports:
        - "3000"
mongodb:
    build: ./mongodb
    ports:
        - "27017"
